#define ROW_TITLE 1
#define ROW_ELAPSED_TIME 1
#define ROW_LAST_COMMAND 3
#define ROW_SWITCH_TABLE 5
#define ROW_TRAIN 10
#define ROW_USER_INPUT 22
#define ROW_DEBUG 40
#define ROW_DEBUG_2 50
#define ROW_BOTTOM 60

#define ROW_CURRENT 2
#define ROW_NEXT 3
#define ROW_STATUS 4
#define ROW_ROUTE 5

#define COLUMN_FIRST 1
#define COLUMN_WIDTH 8
#define COLUMN_VALUES COLUMN_WIDTH * 2 + 1
#define COLUMN_DATA_WIDTH 16
#define COLUMN_DATA_1 COLUMN_DATA_WIDTH + 1
#define COLUMN_DATA_2 COLUMN_DATA_WIDTH * 3 + 1
#define COLUMN_ELAPSED_TIME 70

#define HEIGHT_SWITCH_TABLE 6
#define WIDTH_SWITCH_TABLE 4

#define HEIGHT_TRAIN 5

#define WIDTH_DEBUG 40
